"""Starter chilled-water map. Addresses are placeholders until matched to the controller."""

from __future__ import annotations

import copy

ROLES = [
    {"id": "supply_temp", "label": "Chilled water supply", "kind": "analog"},
    {"id": "return_temp", "label": "Chilled water return", "kind": "analog"},
    {"id": "setpoint", "label": "Setpoint", "kind": "analog"},
    {"id": "capacity", "label": "Capacity", "kind": "analog"},
    {"id": "condenser_in", "label": "Condenser inlet", "kind": "analog"},
    {"id": "condenser_out", "label": "Condenser outlet", "kind": "analog"},
    {"id": "flow", "label": "Chilled water flow", "kind": "analog"},
    {"id": "pressure", "label": "Chilled water pressure", "kind": "analog"},
    {"id": "compressor", "label": "Compressor", "kind": "bool"},
    {"id": "evap_pump", "label": "Evaporator pump", "kind": "bool"},
    {"id": "cond_pump", "label": "Condenser pump", "kind": "bool"},
    {"id": "alarm", "label": "General alarm", "kind": "bool"},
]


def _point(**overrides) -> dict:
    point = {
        "id": "",
        "name": "",
        "group": "General",
        "notes": "",
        "function": "holding",
        "addressing": "modicon",
        "address_number": 40001,
        "dtype": "uint16",
        "byte_order": "ABCD",
        "bit": None,
        "scale": 1.0,
        "offset": 0.0,
        "decimals": 0,
        "unit": "",
        "widget": "value",
        "gauge_min": 0,
        "gauge_max": 100,
        "alarm_low": None,
        "alarm_high": None,
        "writable": False,
        "force_fc16": False,
        "write_min": None,
        "write_max": None,
        "invert": False,
        "on_label": "On",
        "off_label": "Off",
        "enabled": True,
        "sort": 10,
    }
    point.update(overrides)
    return point


def default_points() -> list[dict]:
    return copy.deepcopy(
        [
            _point(
                id="chw_supply",
                name="CHW supply",
                group="Temperature",
                notes="Leaving chilled water. int16, scale 0.1. Match the address to the controller manual.",
                address_number=40001,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="°C",
                widget="gauge",
                gauge_min=0,
                gauge_max=20,
                alarm_low=4,
                alarm_high=7.6,
                sort=10,
            ),
            _point(
                id="chw_return",
                name="CHW return",
                group="Temperature",
                notes="Entering chilled water.",
                address_number=40002,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="°C",
                widget="gauge",
                gauge_min=0,
                gauge_max=25,
                sort=20,
            ),
            _point(
                id="setpoint",
                name="Setpoint",
                group="Setpoint",
                notes="Active chilled-water setpoint. Writable holding register.",
                address_number=40003,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="°C",
                widget="setpoint",
                gauge_min=0,
                gauge_max=20,
                writable=True,
                write_min=4,
                write_max=15,
                sort=30,
            ),
            _point(
                id="capacity",
                name="Capacity",
                group="Process",
                notes="Running capacity.",
                address_number=40004,
                dtype="uint16",
                unit="%",
                widget="gauge",
                gauge_min=0,
                gauge_max=100,
                sort=40,
            ),
            _point(
                id="cond_in",
                name="Condenser in",
                group="Temperature",
                notes="Condenser water inlet, or rename this point if the machine is air-cooled.",
                address_number=40005,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="°C",
                widget="gauge",
                gauge_min=0,
                gauge_max=50,
                sort=50,
            ),
            _point(
                id="cond_out",
                name="Condenser out",
                group="Temperature",
                address_number=40006,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="°C",
                widget="gauge",
                gauge_min=0,
                gauge_max=55,
                sort=60,
            ),
            _point(
                id="flow",
                name="CHW flow",
                group="Process",
                address_number=40007,
                dtype="int16",
                scale=0.1,
                decimals=1,
                unit="m³/h",
                widget="gauge",
                gauge_min=0,
                gauge_max=40,
                sort=70,
            ),
            _point(
                id="pressure",
                name="CHW pressure",
                group="Process",
                address_number=40008,
                dtype="int16",
                scale=0.01,
                decimals=2,
                unit="bar",
                widget="gauge",
                gauge_min=0,
                gauge_max=6,
                sort=80,
            ),
            _point(
                id="compressor",
                name="Compressor",
                group="Status",
                notes="Bit 0 of status word 40009.",
                address_number=40009,
                dtype="bool",
                bit=0,
                widget="status",
                on_label="Running",
                off_label="Stopped",
                sort=90,
            ),
            _point(
                id="evap_pump",
                name="Evaporator pump",
                group="Status",
                notes="Bit 1 of status word 40009.",
                address_number=40009,
                dtype="bool",
                bit=1,
                widget="status",
                on_label="Running",
                off_label="Stopped",
                sort=100,
            ),
            _point(
                id="cond_pump",
                name="Condenser pump",
                group="Status",
                notes="Bit 2 of status word 40009.",
                address_number=40009,
                dtype="bool",
                bit=2,
                widget="status",
                on_label="Running",
                off_label="Stopped",
                sort=110,
            ),
            _point(
                id="general_alarm",
                name="General alarm",
                group="Alarm",
                notes="Bit 3 of status word 40009.",
                address_number=40009,
                dtype="bool",
                bit=3,
                widget="alarm",
                on_label="Alarm",
                off_label="Normal",
                sort=120,
            ),
            _point(
                id="enable",
                name="Enable",
                group="Status",
                notes="Coil output. The demo compressor runs only while this is on.",
                function="coil",
                address_number=1,
                dtype="bool",
                widget="status",
                writable=True,
                on_label="Enabled",
                off_label="Disabled",
                sort=130,
            ),
            _point(
                id="power",
                name="Power",
                group="Process",
                notes="Float32 across 40011 and 40012, byte order ABCD.",
                address_number=40011,
                dtype="float32",
                decimals=1,
                unit="kW",
                widget="gauge",
                gauge_min=0,
                gauge_max=150,
                sort=140,
            ),
        ]
    )


def default_bindings() -> dict[str, str | None]:
    return {
        "supply_temp": "chw_supply",
        "return_temp": "chw_return",
        "setpoint": "setpoint",
        "capacity": "capacity",
        "condenser_in": "cond_in",
        "condenser_out": "cond_out",
        "flow": "flow",
        "pressure": "pressure",
        "compressor": "compressor",
        "evap_pump": "evap_pump",
        "cond_pump": "cond_pump",
        "alarm": "general_alarm",
    }
